In [1]:
# initializing the matrices using variables L, M, N
L = [[3.7827, 3.3454, 3.2341], [2.2122, 3.5678, 3.9087], [1.1234, 2.8934, 5.9087]]
M = [[3.1234, 3.0987, 3.1234], [2.1111, 3.2222, 3.3333], [1.0987, 1.3456, 5.1234]]
N = [[3.1243, 3.0989, 3.1256], [2.6721, 3.6785, 3.9017], [1.1254, 2.8956, 5.9187]]

# Adding the matrices with lists
def list_add (L, M):
    return [[L[i][j] + M[i][j] for j in range(len(L[0]))] for i in range(len(L))]

# Multiplying the matrices with lists
def list_multiply (L, M):
    return [[sum(L[i][k] * M[k][j] for k in range(len(M))) for j in range(len(M[0]))] for i in range(len(L))]

# Subtracting the matrices with lists
def list_subtract (L, M):
    return [[L[i][j] - M[i][j] for j in range(len(L[0]))] for i in range(len(L))]

print("Matrix Addition using Lists: ", list_add(L,M))
print("Matrix subtraction using list: ", list_subtract(L,M))
print("Matrix multipication using list: ", list_multiply (L,M))
print("\n\n\n")

#Profiling the list operations 
import cProfile
def profile_list_operations():
    list_add(L,M)
    list_subtract(L,M)
    list_multiply (L,M)

cProfile.run('profile_list_operations()')

Matrix Addition using Lists:  [[6.9061, 6.444100000000001, 6.3575], [4.3233, 6.79, 7.242], [2.2221, 4.239, 11.0321]]
Matrix subtraction using list:  [[0.6593, 0.24670000000000014, 0.11070000000000002], [0.10110000000000019, 0.34560000000000013, 0.5754000000000001], [0.024699999999999944, 1.5478000000000003, 0.7852999999999994]]
Matrix multipication using list:  [[22.43066479, 26.852805330000002, 39.53569494], [18.73605675, 23.61065602, 38.8279668], [16.10897299, 20.754939779999997, 43.42603136]]




         73 function calls in 0.000 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.000    0.000 <ipython-input-1-84b93ac7968b>:11(list_multiply)
       36    0.000    0.000    0.000    0.000 <ipython-input-1-84b93ac7968b>:12(<genexpr>)
        1    0.000    0.000    0.000    0.000 <ipython-input-1-84b93ac7968b>:15(list_subtract)
        1    0.000    0.000    0.000    0.000 <ipython-input-1-84b9

In [4]:
import numpy as np

# initializing the matrices using variables L, M, N
L_np = np.array([[3.7827, 3.3454, 3.2341], [2.2122, 3.5678, 3.9087], [1.1234, 2.8934, 5.9087]])
M_np = np.array([[3.1234, 3.0987, 3.1234], [2.1111, 3.2222, 3.3333], [1.0987, 1.3456, 5.1234]])
M_np = np.array([[3.1243, 3.0989, 3.1256], [2.6721, 3.6785, 3.9017], [1.1254, 2.8956, 5.9187]])

# Adding the matrices with numpy
numpy_add = L_np + M_np
# Mul the matrices with lists
numpy_multiply = np.dot(A_np, B_np)

print("Matrix addition result using NumPy:", numpy_add)
print("Matrix multiplication result using NumPy:", numpy_multiply)

#Profiling the numpy operations 
import cProfile
def profile_numpy_operations():
    numpy_add(L_np,M_np)
    numpy_multiply(L_np,M_np)

cProfile.run('profile_numpy_operations()')

Matrix addition result using NumPy: [[ 6.907   6.4443  6.3597]
 [ 4.8843  7.2463  7.8104]
 [ 2.2488  5.789  11.8274]]
Matrix multiplication result using NumPy: [[22.43066479 26.85280533 39.53569494]
 [18.73605675 23.61065602 38.8279668 ]
 [16.10897299 20.75493978 43.42603136]]
         4 function calls in 0.000 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.000    0.000 <ipython-input-4-dfe3678589a5>:18(profile_list_operations)
        1    0.000    0.000    0.000    0.000 <string>:1(<module>)
        1    0.000    0.000    0.000    0.000 {built-in method builtins.exec}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}




<class 'TypeError'>: 'numpy.ndarray' object is not callable